{{- if and .Values.chromeNode.enabled .Values.chromeNode.autoscalingEnabled }}
{{ $hubGraphqlUrlDefault := printf "http://%s.%s:%d/graphql" (include "seleniumGrid.hub.fullname" .) .Release.Namespace (int .Values.hub.port) }}
{{ $hubGraphqlUrl := .Values.chromeNode.hpa.url | default (print $hubGraphqlUrlDefault) }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: selenium-grid-chrome-scaledobject
  namespace: {{ .Release.Namespace }}
  labels:
    deploymentName: {{ template "seleniumGrid.chromeNode.fullname" . }}
spec:
  maxReplicaCount: {{ .Values.chromeNode.maxReplicaCount }}
  scaleTargetRef:
    name: {{ template "seleniumGrid.chromeNode.fullname" . }}
  triggers:
    - type: selenium-grid
    {{- with (unset .Values.chromeNode.hpa "url") }}
      metadata:
        url: {{ $hubGraphqlUrl | quote }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
