{{- if .Values.isolateComponents }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "seleniumGrid.sessionQueue.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: selenium-session-queue
    {{- include "seleniumGrid.commonLabels" . | nindent 4 }}
    {{- with .Values.customLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- with .Values.components.sessionQueue.serviceAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  selector:
    app: selenium-session-queue
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.components.sessionQueue.serviceType }}
  {{- if (and (eq .Values.components.sessionQueue.serviceType "ClusterIP") (.Values.components.sessionQueue.clusterIP)) }}
  clusterIP: {{ .Values.components.sessionQueue.clusterIP | quote }}
  {{- end }}
  ports:
    - name: tcp-ssn-que
      protocol: TCP
      port: {{ .Values.components.sessionQueue.port }}
      targetPort: {{ .Values.components.sessionQueue.port }}
{{- end }}
